### ISSUE TITLE
Kafka messages to IBM MQ

### ISSUE THREAD

**Issue by vivekanandak** [ibm-messaging/kafka-connect-mq-sink#1]
Hi,

Our system has messages processing task in mainframe from MQ. Is there a way we can connect Kafka messages to MQ on mainframe. Does the instructions mentioned in GIT still holds good. .

Thanks,
Vivekananda K

**Comment by AndrewJSchofield** [comment]
Hi. I think they will just work. I'll try to get access to a mainframe queue manager and check it out.

**Comment by AndrewJSchofield** [comment]
I have successfully used this connector with MQ on z/OS.
