### ISSUE TITLE
Mainframe able to see the message a Junk

### ISSUE THREAD

**Issue by lakshmanpython** [ibm-messaging/kafka-connect-mq-sink#17]
Hi All,

we are getting Junk format in Mainframe side ... below is our flow.

################################
We are sending the message from kafka topics >> MQ >> Mainframe MQ.
###############################

Below is our parameters 

name=test-mq-sink
topics=TSINK
tasks.max=1
connector.class=com.ibm.eventstreams.connect.mqsink.MQSinkConnector
mq.queue.manager=XXX.XXX
mq.connection.name.list=XXXXX(1514)
mq.channel.name=XXXX
mq.queue=XXXX
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.storage.StringConverter
mq.message.builder=com.ibm.eventstreams.connect.mqsink.builders.DefaultMessageBuilder

**Comment by katheris** [comment]
Hi @lakshmanpython, is that due to JMS headers being added to the message? Does setting `mq.message.body.jms` to `false` solve the issue?

**Comment by lakshmanpython** [comment]
Hi Katheris

Its not solved, we tried with false and true as well. Can you please suggest on below properties.

name=test-mq-sink
topics=TSINK
tasks.max=1
connector.class=com.ibm.eventstreams.connect.mqsink.MQSinkConnector
mq.queue.manager=XXX.XXX
mq.connection.name.list=XXXXX(1514)
mq.channel.name=XXXX
mq.queue=XXXX
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.storage.StringConverter
mq.message.builder=com.ibm.eventstreams.connect.mqsink.builders.DefaultMessageBuilder

**Comment by AndrewJSchofield** [comment]
I think you need to give a lot more information. What is the format of messages on Kafka? What is the format of messages that you expect on the mainframe? When you say "junk", what do you mean? Is it just in CCSID 1208 when you'd like 537? Would it be appropriate just to transfer the data as an array of bytes (you're currently using strings and that implies a CCSID)?

**Comment by jaasritha** [comment]
> I think you need to give a lot more information. What is the format of messages on Kafka? What is the format of messages that you expect on the mainframe? When you say "junk", what do you mean? Is it just in CCSID 1208 when you'd like 537? Would it be appropriate just to transfer the data as an array of bytes (you're currently using strings and that implies a CCSID)?


you mean producer application need to convert CCSID (expected by Mainframe) and then publish to topic from which MQ Sink connector gets those messages and publish to Mainframe MQ?

**Comment by AndrewJSchofield** [comment]
If you are writing to Kafka exactly what you require on the mainframe, you should configure the ByteArrayConverter instead of the StringConverter. But, you've not said what you're actually trying to achieve so it's hard to figure out what settings you need.

**Comment by jaasritha** [comment]
Hi Andrew, 

Thanks for the technical guidance. We are using kafka terminal to publish data to check if the data reaching to Mainframe.  When we publishing data on the mainframe side it appears as junk or unreadable format. 


So we would need your help what the setting required on MQ sink connector side to see the messages that we are sending from kafka terminal. Lets suppose if mainframe is expecting CCSID 737 then what is that parameter we need to set on the MQ sink connector.

**Comment by AndrewJSchofield** [comment]
I think you have two choices.
1) Generate messages in CCSID 737 on the Kafka topic and use the ByteArrayConverter to send it.
2) Use the StringConverter to generate messages in CCSID 1208, and then use MQGMO_CONVERT on the mainframe to do a codepage conversion.
I would leave `mq.message.body.jms=true` in your configuration.

**Comment by jaasritha** [comment]
Hi Andrew, 

Thanks for suggestion, I have google lot for the java code for CCSID conversion.  :( unable to figure out the CCSID conversion in java.

**Comment by lakshmanpython** [comment]
Hi Andrew

we are unable to send json and string based format to MQ. We are getting junk formats "@@@@@@@"


Please review the properties :::

name=test-mq-sink
topics=TSINK
tasks.max=1
connector.class=com.ibm.eventstreams.connect.mqsink.MQSinkConnector
mq.queue.manager=VVVVV
mq.connection.name.list=XXXXXXX(1514)
mq.channel.name=VVVVVV
mq.queue=BBBBBBBBBB
mq.message.body.jms=true
key.converter=org.apache.kafka.connect.converters.ByteArrayConverter
value.converter=org.apache.kafka.connect.converters.ByteArrayConverter
mq.message.builder=com.ibm.eventstreams.connect.mqsink.builders.ConverterMessageBuilder
mq.message.builder.value.converter=org.apache.kafka.connect.json.JsonConverter
mq.message.builder.value.converter.schemas.enable=false

Kindly help...

**Comment by katheris** [comment]
Hi @lakshmanpython, Can you clarify where you are seeing the junk formats and what format you are sending messages in?

Specifically:
What format do you send the messages into your Kafka Cluster?
What format are you expecting to see in MQ?
What format are you expecting to see in MQ Mainframe?
Are the junk messages you see in MQ or MQ Mainframe or both?

**Comment by lakshmanpython** [comment]
Hi Katheris

What format do you send the messages into your Kafka Cluster?
1) JSON 2) STRING 3)numbericwith ALPHABATICAL (0295110000000YMYBR2404211112018092356ABC 000000000000123456789
What format are you expecting to see in MQ? numbericwith ALPHABATICAL (0295110000000YMYBR2404211112018092356ABC 000000000000123456789 )
What format are you expecting to see in MQ Mainframe? numbericwith ALPHABATICAL (0295110000000YMYBR2404211112018092356ABC 000000000000123456789 )
Are the junk messages you see in MQ or MQ Mainframe or both? yes both we can see.

**Comment by katheris** [comment]
Hi @lakshmanpython, are you expecting the format in your Kafka Cluster to be one of JSON, String or numeric? You would need to run a different connector for each different format since the converters would need to be configured appropriately. Have you read through the data formats section of the README.md to understand how changing the converter and message builder settings will affect the messages as they flow through the connector? https://github.com/ibm-messaging/kafka-connect-mq-sink#data-formats

**Comment by lakshmanpython** [comment]
Hi Katheris

As confirmed from Dev Team, 

they are expecting alphanumeric Format ( 0295110000000YMYBR2404211112018092356ABC 000000000000123456789 ) and we we use below parameters, mainframe end we can see some spaces...

mq.message.body.jms=false
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.storage.StringConverter
mq.message.builder=com.ibm.eventstreams.connect.mqsink.builders.DefaultMessageBuilder

Kindly suggest; Please ignore above reply.

**Comment by lakshmanpython** [comment]
Hi Katheris/Andrew

below is our flow 
Kakfa >> IBM MQ   >> MF IBM MQ >>Minframe

Kindly suggest..

We are able to receive the message from kafka to MQ but we are getting junk character at Mainframe level.

Below are the properties we set at connector worker level.... is any thing to be modify.. please suggest
topics=TSINK
tasks.max=1
connector.class=com.ibm.eventstreams.connect.mqsink.MQSinkConnector
mq.queue.manager=XXXXXX
mq.connection.name.list=XXXXX(1514)
mq.channel.name=CCCCC.SVRCONN
mq.queue=XXXXX.REMOTE
mq.message.body.jms=true
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.storage.StringConverter
mq.message.builder=com.ibm.eventstreams.connect.mqsink.builders.DefaultMessageBuilder

Our message format will be as below ( alphanumeric )
0295110000000YMYSRK2404211112018092356ABC 000000000000123456789

**Comment by AndrewJSchofield** [comment]
Hi, I suggest that you use an MQ tool such as the MQ Console to inspect the messages on the mainframe. In particular, you should check the Format and CodedCharSetId fields in the message descriptor. My guess is that the messages are arriving on the mainframe in CCSID 1208 and the format is MQFMT_STRING. You should also try browsing the messages using the MQ Console and see whether they're junk in that tool or just in your application. I doubt very much that the connector is scrambling the messages, but the way that it's configured might be putting them in a format that the mainframe application does not expect.

**Comment by lakshmanpython** [comment]
Hi Andrew

Thanks for guidance... we will check  with our mainframe MQ team...

We browse message in MQ ( non z/os) ,we can the message in CCSID 1208...  

>> please help to describe more on connector scrambling messages.... (what to perform by mainframe application/mq team)

so that we can pass the message correctly to our mainframe application / mq team to do from their end...

The same functionality for cards application which working from Websphere application server, we are using the same configuration of queue for this usecase...

Kindly suggest

**Comment by AndrewJSchofield** [comment]
If I understand you correctly, the connector is putting the messages in CCSID 1208. I suspect you might need MQGMO_CONVERT in your mainframe applications. The connector does not provide a way of setting the desired CCSID and if you're using the StringConverter, I would expect the messages to be encoded in UTF-8 which is CCSID 1208. If your applications are used to one of the EBCDIC CCSIDs, this could be the source of the difficulties.

So, I suggest you try using MQGMO_CONVERT on the mainframe and seeing if that fixes the problem and makes the messages readable.

**Comment by lakshmanpython** [comment]
Hi Andrew

Thanks Andrew for your guidance and suggestion, 

>>we set at mainframe, now we can able to see the message. But we can see blank message along with that.

>>Why blank messages is coming along with the message. Unable to figure it out.

can you please suggest on this as well.

**Comment by AndrewJSchofield** [comment]
I don't quite understand the "blank messages is coming along with the message". Can you see the blank messages when you use a tool like MQ Console? I cannot think of any reason why the connector would send a blank message unless it consumed a blank message from the Kafka topic.

**Comment by lakshmanpython** [comment]
Thanks @AndrewJSchofield 

Issue solved. Mainframe application corrected from their side. Thanks a lot for your valuable Guidance and suggestion.

Thanks @katheris  for helping

I am keen to watch your conference in upcoming kafka Summit.  !!!!! ALL THE BEST !!!!!!
