### ISSUE TITLE
ReplyToQ

### ISSUE THREAD

**Issue by brust** [ibm-messaging/kafka-connect-mq-sink#19]
A configuration option to set `ReplyToQ` param.

`ReplyToQ` is a local definition of a remote queue used by QM to send report message about a COA (Confirmation Of Arrival) or a COD (Confirmation Of Delivery) event.

**Comment by AndrewJSchofield** [comment]
This seems like a good idea. Is ReplyToQMgr important too?

**Comment by AndrewJSchofield** [comment]
Actually, I can do both with a single property. I'll consider this enhancement for the next release.

**Comment by AndrewJSchofield** [comment]
Support added in v1.1.0.
