### ISSUE TITLE
MessageBuilder for XML?

### ISSUE THREAD

**Issue by joewood** [ibm-messaging/kafka-connect-mq-sink#2]
I'm looking at creating a MessageBuilder for XML messages, so that SinkRecords with Structs are generically convertable to XML in MQ. I wanted to check to see if this is something that would be useful or if there are any known implementations. My thinking is:
* Need to provide some custom parameters on the Schema object to indicate leaf fields that should be serialized as attributes.
* Need to add support for other custom parameters for namespace reference etc..
* Use Jackson with a custom formatter to apply rules for attributes etc..

**Comment by AndrewJSchofield** [comment]
Hi, this sounds like a good idea. I'm not aware of any existing implementation.

**Comment by AndrewJSchofield** [comment]
This isn't something I'm interested in adding at this time. You're welcome to make a pull request.
