### ISSUE TITLE
Kafka sink connectors dumping duplicate messages to IBM MQ

### ISSUE THREAD

**Issue by harishanandan124** [ibm-messaging/kafka-connect-mq-sink#22]
We have deployed the Connectors provided in a Clustered Environment by installing the Connectors to different hosts and have Load Balancer (Active-Active) to distribute the traffic. When using the Sink Connector, we have a typical problem where the source is Kafka topic (single) and somehow the same record is being processed by both the Connectors resulting in sending duplicate message to IBM MQ queue. Can you please let me know if there is any configuration setting that is missing for this issue.

**Comment by katheris** [comment]
Hi, can you provide the configuration that you are using for starting the two connectors? The connectors use an auto-generated consumer groupId which is based on the name of the connector. If you start both connectors with the same name, each running in a different KafkaConnect instance they should have the events split between them.

**Comment by AndrewJSchofield** [comment]
Closing dormant issue.
