### ISSUE TITLE
Suggestion: enable Converter class to be configured on MessageBuilder

### ISSUE THREAD

**Issue by joewood** [ibm-messaging/kafka-connect-mq-sink#3]
Given the MessageBuilder delegates most of its functionality to a `Converter`, would it make sense to be able to configure the DefaultMessageBuilder with a `Converter` class, in the same way as Connectors use converters to serialize/deserialize Kafka messages? This way a custom `Converter` could be plugged into the MQ Connectors without any additional work.

**Comment by AndrewJSchofield** [comment]
Hi, I think this is a good idea. I'd be happy to receive a pull request if you're keen, or you could wait for me to refresh the connector.

**Comment by AndrewJSchofield** [comment]
Done. Try the ConverterMessageBuilder.
