### ISSUE TITLE
MQ connector not listed

### ISSUE THREAD

**Issue by balajikadambi** [ibm-messaging/kafka-connect-mq-sink#32]
Hi,

We tried deploying the MQ connector standalone and also inside the container. We followed the instructions given in the GitHub README.
The connector is not getting listed when we run the below commands:

```
$ curl http://localhost:8083
{"version":"2.5.0","commit":"66563e712b0b9f84","kafka_cluster_id":"jYm3VyL3RgS92suAs1GRXg"}
```

```
$ curl http://localhost:8083/connectors
[]
```
Could you help resolve the issue.

Thanks,
Balaji

**Comment by AndrewJSchofield** [comment]
It doesn't sound like an instance of the connector has been started. If you do:
```
$ curl http://localhost:8083/connector-plugins
```
you should see the MQ connector listed.

I've never actually used the REST interface against the standalone worker, but for the distributed worker, you should definitely see the running connector listed when you GET `http://localhost:8083/connectors`.

**Comment by balajikadambi** [comment]
@AndrewJSchofield when I run the command you provided it is listed.
```
$ curl http://localhost:8083/connector-plugins
[{"class":"com.ibm.eventstreams.connect.mqsink.MQSinkConnector","type":"sink","version":"1.3.0"},
{"class":"org.apache.kafka.connect.file.FileStreamSinkConnector","type":"sink","version":"2.5.0"},{"class":"org.apache.kafka.connect.file.FileStreamSourceConnector","type":"source","version":"2.5.0"},
{"class":"org.apache.kafka.connect.mirror.MirrorCheckpointConnector","type":"source","version":"1"},
{"class":"org.apache.kafka.connect.mirror.MirrorHeartbeatConnector","type":"source","version":"1"},
{"class":"org.apache.kafka.connect.mirror.MirrorSourceConnector","type":"source","version":"1"}]
```
But the command http://localhost:8083/connectors does not list anything.

I ran the command - docker run -v $(pwd)/config:/opt/kafka/config -p 8083:8083 kafkaconnect-with-mq-sink:0.0.1 to start the container.

**Comment by AndrewJSchofield** [comment]
You'll need to start the connector like this: https://github.com/ibm-messaging/kafka-connect-mq-sink#running-in-distributed-mode

**Comment by balajikadambi** [comment]
@AndrewJSchofield When I start connect inside the container, is it not in distributed mode?
I see this command in the docker file:
ENTRYPOINT ["./bin/connect-distributed.sh", "config/connect-distributed.properties"]

**Comment by AndrewJSchofield** [comment]
Yes, it is in distributed mode, and that's why there's a separate step to start the connector.

**Comment by balajikadambi** [comment]
Thanks @AndrewJSchofield.  After starting the connector, it gets listed. Closing the issue.
