### ISSUE TITLE
Configure connector at start of Docker container

### ISSUE THREAD

**Issue by max-weis** [ibm-messaging/kafka-connect-mq-sink#34]
Hi,

I'm trying to run the connector inside a container, but I want to configure the connector without a HTTP call. 

With a POST request I can create the connector, but mounting the `mq-sink.properties` to the config dir doesn't do anything.
I also tried to clone the code and change the Dockerfile to use the `mq-sink.properties` in the entrypoint line. Which did nothing as well

Is that even possible to achieve?

**Comment by AndrewJSchofield** [comment]
If the connector is running in distributed mode, you'll need an initial HTTP call to kick the connector off. If you're doing it in standalone mode, the configuration file is sufficient.

**Comment by max-weis** [comment]
alright, thank you!
