### ISSUE TITLE
Sink connector is slow

### ISSUE THREAD

**Issue by jay999123** [ibm-messaging/kafka-connect-mq-sink#35]
Hi,
I'm using sink connector to publish messages to MQ queue. When the connector started, we observed that there's a delay in sending each message. There're almost 5 seconds delay between each message. The mainframe that's sitting on the other side of the MQ is expecting the messages in milli-seconds.
I've tried increasing the `tasks.max` to `5` since I've 10 partitions on the topic. But still same issue. There's a delay in sending the messages.

Any suggestions on how to decrease the latency?
---------
We're using one worker btw.
Thanks,

**Comment by AndrewJSchofield** [comment]
Hi,
I have tested the connector at over 5000 messages/second. It's designed as a long-running tool that continuously copies messages between Kafka and MQ. Could you explain the way that you're sending messages and how you're measuring the delay? If you're sending one message and waiting for its arrival, and then another and waiting for its arrival, I can well imagine there's a multi-second "delay"? It's designed to batch the messages for efficiency.

**Comment by jay999123** [comment]
Hello,
Below are my properties :
`{
    "name": "MQ_Sink_Connector",
    "config":
    {
        "connector.class": `"com.ibm.eventstreams.connect.mqsink.MQSinkConnector",`
        "tasks.max": "5",
        "topics": "topic_test_abc",
        "key.converter": "org.apache.kafka.connect.converters.ByteArrayConverter",
        "value.converter": "org.apache.kafka.connect.converters.ByteArrayConverter",		
		"mq.user.name": "ABCD",		
        "mq.queue.manager": "MQ12",
        "mq.connection.name.list": "A.B.C.D(1111)",
        "mq.channel.name": "AB.MQ12.TEST",
        "mq.queue": "AB.LOCAL.TEST.QUEUE",
        "mq.message.builder": "com.ibm.eventstreams.connect.mqsink.builders.DefaultMessageBuilder"
    }
}`

And based on the logs of the worker - 
`**key to be sent to MQ** - SysOut-- r.key():: {}[[B@3979999b]timestamp::2020-07-13 06:57:01.918
**Message to be sent to MQ** - SysOut-- r.value():: {}[[B@476bbc4a]timestamp::2020-07-13 06:57:01.918
2020-07-13 18:57:01,924 INFO WorkerSinkTask{id=MQ_Sink_Connector_TLDTL_GM1C_DEV-0} Committing offsets asynchronously using sequence number 4235: {topic_mq_series_sink-dev-1=OffsetAndMetadata{offset=5448, metadata=''}, topic_mq_series_sink-dev-0=OffsetAndMetadata{offset=5292, metadata=''}} (org.apache.kafka.connect.runtime.WorkerSinkTask) [pool-16-thread-3]
2020-07-13 18:57:02,405 INFO SinkRecord :: SinkRecord{kafkaOffset=5448, timestampType=CreateTime} ConnectRecord{topic='topic_mq_series_sink-dev', kafkaPartition=1, key=[B@52333e76, value=[B@0099e4d73, timestamp=1594666622378, headers=ConnectHeaders(headers=)} (com.ibm.eventstreams.connect.mqsink.JMSWriter) [pool-16-thread-3]
2020-07-13 18:57:02,405 INFO Message record to be sent to MQ :: 
  JMSMessage class: jms_bytes
  JMSType:          null
  JMSDeliveryMode:  2
  JMSDeliveryDelay: 0
  JMSDeliveryTime:  0
  JMSExpiration:    0
  JMSPriority:      4
  JMSMessageID:     null
  JMSTimestamp:     0
  JMSCorrelationID: null
  JMSDestination:   null
  JMSReplyTo:       null
  JMSRedelivered:   false
ffffffffff6f5f9f8f4f6d8
 (com.ibm.eventstreams.connect.mqsink.JMSWriter) [pool-16-thread-3]
**key to be sent to MQ** - SysOut-- r.key():: {}[[B@41255556]timestamp::2020-07-13 06:57:02.405
**Message to be sent to MQ** - SysOut-- r.value():: {}[[B@9898983]timestamp::2020-07-13 06:57:02.405`

In the logs as you can see, there are appro., 485 ms difference between each request and sometime it goes upto 1 or 2 seconds difference.
And I'm sending messages to topic using a `Producer` 
--------------------------------------------(`configuration from the worker log are given below`)--------------------
**Worker Config** are given below :
Starting Kafka connect with configuration:<br/>
rest.port=8083
rest.advertised.host.name=2.12.1.1 
rest.advertised.port=8083
bootstrap.servers=broker1:9092,broker2:9092,broker3:9092
group.id=connect-sink-mq
offset.storage.topic=connect-sink-mq-offsets
config.storage.topic=connect-sink-mq-configs
status.storage.topic=connect-sink-mq-status
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=true
value.converter.schemas.enable=true
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false
plugin.path=/app/confluent-5.0.0/share/java
config.storage.replication.factor=3
offset.storage.replication.factor=3
status.storage.replication.factor=3
offset.flush.interval.ms=2000
----------------------------
**Consumer Config :**
max.poll.records = 500 
max.partition.fetch.bytes = 1048576
fetch.min.bytes = 1
fetch.max.bytes = 52428800
auto.commit.interval.ms = 5000
auto.offset.reset = earliest
enable.auto.commit = false
--------------------------
**Producer Config:**
acks = all
batch.size = 16384
linger.ms = 0
---------------

**Comment by AndrewJSchofield** [comment]
I still don't quite know what your messaging pattern is here. The connector is designed to work with a sustained load of messages and process them efficiently in batches. It cares about throughput more than latency. It's not designed to move individual messages with low latency between the two systems, although if you familiarise yourself with the configuration of the Kafka Connect workers, you should be able to minimise batching delays.

**Comment by jay999123** [comment]
My messaging pattern is - 
Kafka Producer (most of the settings are default) -> Topic -> sink connector -> MQ
Since I'm not explicitly setting any `batch.size` in the `producer`, the default settings are applied. Do you think increasing the `batch.size` would be of any help?

**Comment by AndrewJSchofield** [comment]
I think you need to tune the Kafka consumer which is used by the Kafka Connect worker.

**Comment by AndrewJSchofield** [comment]
Closing dormant issue.
