### ISSUE TITLE
Acknowledge on message delivery from Kafka to MQ

### ISSUE THREAD

**Issue by bensooraj** [ibm-messaging/kafka-connect-mq-sink#36]
Hi!

I am just familiarising myself with the MQ sink and source connectors. I want to thank you for this project and for all your efforts.

I have a question, is there someway I can get an acknowledge that the message has been actually sent to or delivered IBM MQ from Kafka? Maybe using the topic offset?

For example, when I do an `MQ PUT` using the [mq-mqi-nodejs](https://github.com/ibm-messaging/mq-mqi-nodejs) npm module I know for sure whether the request failed or not along with Message ID in the MQ Message Descriptor:

https://github.com/ibm-messaging/mq-mqi-nodejs/blob/932f5768e48cebe11697470c3fbdc46bea8a43ba/samples/amqsput.js#L66-L71

Thanks!

**Comment by bensooraj** [comment]
A gentle bump!

Would really appreciate any insights on this question.

**Comment by AndrewJSchofield** [comment]
Hi, I'm afraid not. The Kafka producer and consumer APIs are hidden away in the Kafka Connect runtime.

**Comment by bensooraj** [comment]
Thanks, @AndrewJSchofield for letting me know.
