### ISSUE TITLE
Suggestion: add support for multiplexing out to multiple queues

### ISSUE THREAD

**Issue by joewood** [ibm-messaging/kafka-connect-mq-sink#4]
Add support for multiple queues and channels from a single topic by deriving the queue name from content in the message.  A couple of potential approaches:
* Use a configuration to derive the queue name from a field in the structured payload (e.g. a field in SinkRecord and key)
* Configure a class that contains a function that returns the queue name, channel etc. from a SinkRecord

**Comment by AndrewJSchofield** [comment]
Hi, this isn't something that I'm interested in pursuing personally. There's a lot of complexity involved if each message potentially uses a different queue. There are limits in the queue manager, limits in terms of memory usage and so on. So, I'd rather not complicate the connector like this.
