### ISSUE TITLE
Does the connector batch messages before put in the mq queue?

### ISSUE THREAD

**Issue by JPCamargo** [ibm-messaging/kafka-connect-mq-sink#44]
Does The IBM MQ sink connector batch messages when it is producing to the MQ queue or the connector puts the messages one by one on the queue?

Actually there isn't any connector configuration related to batch messages.

**Comment by dalelane** [comment]
They're not batched, although they are all committed together in a transaction.

Essentially, Kafka Connect fetches any messages that are on the Kafka topic. The Connector sends these to the MQ queue one at a time using [`JMSProducer.send`](https://docs.oracle.com/javaee/7/api/javax/jms/JMSProducer.html#send-javax.jms.Destination-javax.jms.Message-). And then the transaction is committed using [`JMSContext.commit`](https://docs.oracle.com/javaee/7/api/javax/jms/JMSContext.html#commit--)
