### ISSUE TITLE
mq.jms.properties.copy.to.kafka.headers for MQ sink connector

### ISSUE THREAD

**Issue by pierre-degrandmaison** [ibm-messaging/kafka-connect-mq-sink#45]
MQ source connector has mq.jms.properties.copy.to.kafka.headers
Whether to copy JMS message properties to Kafka headers

I was expecting the reverse for the MQ sink connector, but the closer I found was this:
mq.message.builder.topic.property
The JMS message property to set from the Kafka topic

it seams to be set from Kafka topic? not Kafka header? I did not find any example of "mq.message.builder.topic.property".

is there an MQ sink equivalent to MQ source mq.jms.properties.copy.to.kafka.headers??

**Comment by andrijadukic-syntio** [comment]
Is there any update regarding this? This seems like it should be done by default, as you would expect the Kafka record headers to be mapped seamlessly to the IBM MQ equivalent. It seems to me this could simply be added to the BaseMessageBuilder class by iterating through the Kafka headers.

**Comment by dalelane** [comment]
Closing as this has now been implemented in [Release 1.4.0](https://github.com/ibm-messaging/kafka-connect-mq-sink/releases/tag/v1.4.0)
