### ISSUE TITLE
Setting message expiry

### ISSUE THREAD

**Issue by j0xaf** [ibm-messaging/kafka-connect-mq-sink#48]
Reading the source code I think it is currently not possible to set message expiry (`message.setExpiration(long)`). Is that correct? Would you accept a pull request implementing this?

Thanks for the great connector, btw.

**Comment by jhughes24816** [comment]
Hi @j0xaf, sorry for the delayed response. This would be an interesting feature to add. Would this be something you would want to apply to all the messages being sent to a queue?

I will raise this with the development team and hopefully we can work out a suitable implementation in this issue.

**Comment by j0xaf** [comment]
> Hi @j0xaf, sorry for the delayed response. This would be an interesting feature to add. Would this be something you would want to apply to all the messages being sent to a queue?
> 
> 
> 
> I will raise this with the development team and hopefully we can work out a suitable implementation in this issue.

Yeah, I'd apply it to all messages sent to the queue. In the simplest scenario this could be a configuration constant, in a slightly more elaborate one the TTL could also be taken from a Kafka Header. What do you think?

**Comment by jhughes24816** [comment]
Hi there, 

This simplest functionality is already available by making use of the `mq.time.to.live` setting for the connector. This can be set in the connector properties and will configure the `JMSwriter` such that all the messages it produces to mq have the time to live equal to the value of this property in ms (if this is set to 0 which it is by default the the message will not expire).
(For reference you can find this in the configurable properties in the README and it is also an option defined in the (JMSwriter class)[https://github.com/ibm-messaging/kafka-connect-mq-sink/blob/af9111de2f389198b263d5f448829100200fa9df/src/main/java/com/ibm/eventstreams/connect/mqsink/MQSinkConnector.java#L81])

Let me know how you get on with that and I will take a look at how we might consider implementing a per message method of setting the expiry. On my initial glance this might be possible in a couple of ways so I will see what is the most suitable solution.

**Comment by j0xaf** [comment]
Hi @jhughes24816, don't know how I missed that, but that fits of course the requirements. Thanks for pointing it out! Closing the issue.
