### ISSUE TITLE
Error: Must configure one of topics or topics.regex

### ISSUE THREAD

**Issue by daniel11609** [ibm-messaging/kafka-connect-mq-sink#49]
Hi there,

I cannot make the connector work.

Kafka Cluster: confluent cloud (works via console producer / consumer)
MQ server: IBM Cloud 

Error when launching the connector:
"Must configure one of topics or topics.regex"
![image](https://user-images.githubusercontent.com/19250367/188893672-f21dcdb2-0f05-45df-9f38-cdcdc8769d54.png)

content of mq-sink.properties (topic is defined and exists)
![image](https://user-images.githubusercontent.com/19250367/188893989-aa4c9fe2-dcf0-4e1f-8069-d651a6a5cdf6.png)

connect-standalone.properties are correct, works via console producer / consumer

MQ connection via JMS works when testing it.

Anybody facing the same issues  or has a hint?

**Comment by jhughes24816** [comment]
Hi @daniel11609, did you get this to work?

**Comment by daniel11609** [comment]
Hey,
No I did not. But haven't really tried much.

**Comment by daniel11609** [comment]
@jhughes24816 was it fixed or what is the solution?

**Comment by jhughes24816** [comment]
@daniel11609 I was not able to reproduce this in testing
