### ISSUE TITLE
The connector doesn't transfer Kafka headers to JMS properties

### ISSUE THREAD

**Issue by andrijadukic-syntio** [ibm-messaging/kafka-connect-mq-sink#52]
Kafka headers can contain important information which can't be lost as part of sinking records to IBM MQ.
[The IBM MQ Sink Connector by Confluent ](https://docs.confluent.io/kafka-connectors/ibmmq-sink/current/overview.html#forwarding-kafka-properties-to-jms) has exactly this functionality, as it's a requirement in countless use cases.

The source connector implemented by IBM has the equivalent feature which copies over JMS message properties as Kafka headers (mq.jms.properties.copy.to.kafka.headers) but the sink connector is missing this.

This seems like a bug/missing feature to me, so are there plans to add this, or is there a reason why this is missing?

**Comment by dalelane** [comment]
@andrijadukic-syntio Thanks for the suggestion. I suspect this should be straightforward to add, so we'll look into it.

**Comment by dalelane** [comment]
@andrijadukic-syntio I've added the config option `mq.kafka.headers.copy.to.jms.properties` as part of [release 1.4.0](https://github.com/ibm-messaging/kafka-connect-mq-sink/releases/tag/v1.4.0) 

Please let us know if this does what you need, and thanks again for the suggestion.

**Comment by andrijadukic-syntio** [comment]
> @andrijadukic-syntio I've added the config option `mq.kafka.headers.copy.to.jms.properties` as part of [release 1.4.0](https://github.com/ibm-messaging/kafka-connect-mq-sink/releases/tag/v1.4.0)
> 
> Please let us know if this does what you need, and thanks again for the suggestion.

@dalelane I've tried it out and it's working as expected now: the headers are being transferred over to IBM MQ and vice versa. 
Thanks for responding to my issue and implementing the feature so quickly, it's much appreciated :)

Also, just letting you know that I believe the following issue can also be closed https://github.com/ibm-messaging/kafka-connect-mq-sink/issues/45, although I'm not 100% sure if this is what the original author meant.
