### ISSUE TITLE
Building mq connector on Docker fails -> apache kafka 3.4.0 repo is not available anymore

### ISSUE THREAD

**Issue by giovanni-savino** [ibm-messaging/kafka-connect-mq-sink#58]
If I try to build mq sink connector on Docker, it fails on step

```
RUN mkdir /opt/kafka \
    && tar -xf kafka.tgz -C /opt/kafka --strip-components=1
    
```
Error:
 ```
tar: invalid tar magic
Error: building at STEP "RUN tar -xf kafka.tgz -C /opt/kafka --strip-components=1": while running runtime: exit status 1
 ```

since the curl on file https://downloads.apache.org/kafka/3.4.0/kafka_2.12-3.4.0.tgz fails, because the remote repo is not more available. 

Current available repo on https://downloads.apache.org/kafka are:
* 3.4.1
* 3.5.0
* 3.5.1

The Dockerfile line could be updated to:
```
RUN curl -L "https://downloads.apache.org/kafka/3.5.1/kafka_2.13-3.5.1.tgz" -o kafka.tgz
```

**Comment by jhughes24816** [comment]
Hi @giovanni-savino we have just merged a [PR](https://github.com/ibm-messaging/kafka-connect-mq-sink/pull/57) for this. Thanks for the heads up.
