### ISSUE TITLE
Start the connector worker replacing `<connector-root-directory>`:

### ISSUE THREAD

**Issue by clementjk59** [ibm-messaging/kafka-connect-mq-sink#6]
CLASSPATH=<connector-root-directory>/target/kafka-connect-mq-sink-0.3-SNAPSHOT-jar-with-dependencies.jar bin/kafka-connect-standalone config/connect-standalone.properties ~/mq-sink.properties

Whats the similar command in Windows. i tried with PATH and i dont see logs .
I rearranged to 
>connect-standalone config\connect-standalone.properties config\mq-sink.properties
got error as "Failed to find any class that implements Connector and .." 
Seems like the command is not able to locate the generated JAR file, but i can see the jar in PATH. 
Any help is appreciated. Thanks.

**Comment by AndrewJSchofield** [comment]
I'm not quite sure and I don't have a Windows system to try it. Basically, you need the connector's JAR on the classpath. I would expect that adding that JAR to the CLASSPATH environment variable would work.
