### ISSUE TITLE
How can I use MQMD fields?

### ISSUE THREAD

**Issue by joaothallis** [ibm-messaging/kafka-connect-mq-sink#63]
I see that it have implemented [ReplyToQ](https://www.ibm.com/docs/en/SSFKSJ_9.4.0/refdev/q097660_.html) and [ReplyToQMgr](https://www.ibm.com/docs/en/SSFKSJ_9.4.0/refdev/q097670_.html) (https://github.com/ibm-messaging/kafka-connect-mq-sink/issues/19). 

Is that possible to user other fields like [Report](https://www.ibm.com/docs/en/SSFKSJ_9.4.0/refdev/q097680_.html), [MsgType](https://www.ibm.com/docs/en/SSFKSJ_9.4.0/refdev/q097570_.html), [Persistence](https://www.ibm.com/docs/en/SSFKSJ_9.4.0/refdev/q097600_.html), [CodedCharSetId](https://www.ibm.com/docs/en/SSFKSJ_9.4.0/refdev/q097460_.html) and how do I use then?

**Comment by Joel-hanson** [comment]
@joaothallis We've introduced new configurations for the connector that allow additional control information to be included with the message data before it is sent to MQ. For more details, please refer to the documentation here: https://ibm.github.io/event-automation/es/connecting/mq/sink/#enabling-mqmd.

**Comment by Joel-hanson** [comment]
Closing this for now, Please reopen if the docs doesn't satisfy.
