### ISSUE TITLE
Sending Kafka headers to MQ via mq.kafka.headers.copy.to.jms.properties

### ISSUE THREAD

**Issue by ChameleonTartu** [ibm-messaging/kafka-connect-mq-sink#64]
Hei,

I am in the middle of debugging communication between the Kafka MQ Sink connector and MQ.

It looks like setting `mq.kafka.headers.copy.to.jms.properties` to true fills JMS properties, but properties aren't set in MQ itself.

Do you have any suggestions on the configuration that may be relevant? 

We also use this property:

`"mq.message.builder": "com.ibm.eventstreams.connect.mqsink.builders.JsonMessageBuilder"`

**Comment by ChameleonTartu** [comment]
The answer is simple but rather non-obvious for me.

Without specifying param, `mq.message.body.jms`, MQ received messages in `MQSTR` format after setting `mq.message.body.jms=true`, messages became `MQRFH2` format which was a desired behavior.

**Conclusion:**
Everything works, but for setting JMS properties as headers in MQ, we need these two params:
```
mq.kafka.headers.copy.to.jms.properties=true
mq.message.body.jms=true
```

**Comment by dalelane** [comment]
thanks very much for taking the time to share the answer!
