### ISSUE TITLE
Configure multiple MQ sink in one jar file

### ISSUE THREAD

**Issue by hiren39002** [ibm-messaging/kafka-connect-mq-sink#8]
Hello
  How can i configure multiple SinkConnector in one jar file and initiate it.
   issue: in my project i have more then one Queues to sink with different topics.  
  for example: topic1 --> mq1
                         topic2 --> mq2 

  How can i configure it? Do i need to create multiple mq-sink projects for that or i can configure it in one project?

**Comment by AndrewJSchofield** [comment]
Hi, you should be able to use a single JAR and two separate configurations. For example, if you're using the standalone worker, just run two of them with two separate configurations.

**Comment by hiren39002** [comment]
got it Thank you! 
one more question : How can i read selected messages from kafka mq source? 
Like i have a message correlation id and i need to read only those messages with correlation id not all.
I have scenario that i need to pass correlation id in topic and from karka-source-mq i need to read messages using that correlation id.

**Comment by AndrewJSchofield** [comment]
You'd have to make a change to the source code. That's the beauty of open source :) You can start with what I provided and add a filter on correlation ID. The correlation ID is available in the JMS API. You could for example add a check for the correlation ID into the JMSReader.receive() method.

**Comment by hiren39002** [comment]
thank you! Got that part but how can i pass Correlation ID Demoapplication --> Topic --> JMSReader ?

**Comment by AndrewJSchofield** [comment]
If I've understood correctly, the scenario is that you have messages on an MQ queue that have correlation IDs. You are then trying to use the MQ source connector to put them onto a Kafka topic but you only want messages that match a specific correlation ID. Is that right?

**Comment by hiren39002** [comment]
yes partially. The scenario like this
i have 2 queues q1,q2  and two topics t1,t2
1) i read message from q1 and put them on topic t1.
3) i read the correlation id from topic t1 and pass it to topic t2. 
4)  now from MQ connector pass correlation id to queue q2 receive method . 
5) send that message back to topic t2.

i don't know is it possible to pass variable(correlation ID) in KafkaListner?

or 

Is there any way I can read specific messages from KafkaListner? Like read only those which has particular correlation ID.

**Comment by AndrewJSchofield** [comment]
Could you please update your description a bit. For example, "I read message from MQ queue q1 and put them on Kafka topic t1." Just so I'm totally clear which topics are MQ and which are Kafka. Since both have topics, I'd like to be clear.

**Comment by hiren39002** [comment]
1) i read message from MQ queue q1 and put them on Kafka topic t1.
2) i read message from Kafka topic1  which has message Correlation ID. 
3) i need to pass  that Correlation id in Kafka topic t2, which is listener topic connected to MQ queue q2.
4) read message from MQ queue q2 and pass it to kafka topic t2.

or 

1) i read message from MQ queue q1 and put them on Kafka topic t1.
2) i read message from MQ queue q2 and put them on Kafka topic t2.
3) read Kafka topic t2  but read only those messages which has  correlation ID.

**Comment by AndrewJSchofield** [comment]
When the messages are received into the MQ source connector, they come into the JMSReader class in the receive() method as JMS messages. The correlation ID can be obtained from a JMS message using the getJMSCorrelationID method. So, you could add some code at line 197:
 https://github.com/ibm-messaging/kafka-connect-mq-source/blob/master/src/main/java/com/ibm/mq/kafkaconnect/JMSReader.java#L197

You could write something like:

String correlid = m.getJMSCorrelationID();

Then, you should only call the builder.toSourceRecord() method if the correlid matches the one you're interested in. If it doesn't match, you just read it off the MQ queue but you don't create a Kafka SourceRecord. This has the effect of filtering the messages that end up on the Kafka topic.

Hope this helps.

**Comment by AndrewJSchofield** [comment]
I have just released a new version of the connector. While it doesn't quite do the filtering that you described, it does show how to handle the JMS correlation id, so it's now very close and you could more easily adapt it to do exactly what you want. Hope this helps.
